// DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
// Look at mod.c for mod code

// PS3 system includes
#include <sys/prx.h>
#include <sys/tty.h>
#include <sys/syscall.h>

#include "lib/common.h"
#include "lib/shk.h"
#include "lib/config.h"

#include "modulelist.h"

// PRX initialization boilerplate
s32 _start( void );
SYS_MODULE_INFO( modPrx, 0, 1, 1 );
SYS_MODULE_START( _start );
SYS_MODULE_STOP( _stop );

// runtime initialisation
extern void* _shk_elf_prx_ptr_table;
extern void* _shk_prx_ptr_table;
extern void _runtimeSubstitute1Impl();
SHK_HOOK( void, _runtimeSubstitute1 );

void _runtimeInit()
{
    printf( "modprx: initialising runtime\n" );

    // initialize pointer to prx function pointer table in elf
    *(void**)&_shk_elf_prx_ptr_table = &_shk_prx_ptr_table;

    // bind hook to function that was substituted (copied to the prx) to make room for the loader
    SHK_BIND_HOOK( _runtimeSubstitute1, _runtimeSubstitute1Impl );
    
    printf( "modprx: runtime initialised\n" );
}

s32 _start( void )
{
    printf( "modprx: initialising\n" );
    _runtimeInit();

    // load config
    printf( "modprx: loading config\n" );
    configLoad( "config.yml" );

    printf( "modprx: initialising modules\n" );
    u32 moduleCount = sizeof( Modules ) / sizeof( ModuleInfo );
    for ( u32 i = 0; i < moduleCount; ++i )
    {
        ModuleInfo* info = &Modules[i];
        ConfigSetting* toggleSetting = configGetSettingByName( info->toggleSettingName );

        if ( toggleSetting && toggleSetting->valueType == CONFIG_VALUE_TYPE_BOOL && toggleSetting->value.boolValue )
        {
            printf( "modprx: initialising module %s (%s)\n", info->longName, info->shortName );
            info->init();
        }
        else
        {
            printf( "modprx: module %s (%s) disabled in config, skipping\n", info->longName, info->shortName );
        }
    }
    
    return SYS_PRX_START_OK;
}

s32 _stop( void )
{
    printf( "modprx: shutting down\n" );

    printf( "modprx: shutting down modules\n" );
    u32 moduleCount = sizeof( Modules ) / sizeof( ModuleInfo );
    for ( u32 i = 0; i < moduleCount; ++i )
    {
        ModuleInfo* info = &Modules[i];
        ConfigSetting* toggleSetting = configGetSettingByName( info->toggleSettingName );

        if ( toggleSetting && toggleSetting->valueType == CONFIG_VALUE_TYPE_BOOL && toggleSetting->value.boolValue )
        {
            printf( "modprx: shutting down module %s (%s)\n", info->longName, info->shortName );
            info->shutdown();
        }
    }

    printf( "modprx: shutdown finished\n" );
    return SYS_PRX_STOP_OK;
}
