// DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING

// PS3 system includes
#include <sys/prx.h>
#include <sys/tty.h>
#include <sys/syscall.h>

#include "lib/common.h"
#include "lib/shk.h"
#include "lib/config.h"
#include "lib/module.h"

// PRX initialization boilerplate
s32 _start( void );
SYS_MODULE_INFO( modPrx, 0, 1, 1 );
SYS_MODULE_START( _start );
SYS_MODULE_STOP( _stop );

// runtime initialisation
extern void* _shk_elf_prx_ptr_table;
extern void* _shk_prx_ptr_table;
extern void _shk_prx_elf_substitute_impl();
SHK_HOOK( void, _shk_prx_elf_substitute );

#define LOADER_TRACE_LOG 0
#define LOADER_LOG( msg, ... ) printf( "modprx loader: " msg, ##__VA_ARGS__ )
#if LOADER_TRACE_LOG
#define LOADER_TRACE( msg, ... ) printf( "modprx loader: " msg, ##__VA_ARGS__ )
#else
#define LOADER_TRACE( msg, ... ) do {} while ( false )
#endif

void initRuntime()
{
    LOADER_LOG( "initialising runtime\n" );

    // initialize pointer to prx function pointer table in elf
    *(void**)&_shk_elf_prx_ptr_table = &_shk_prx_ptr_table;

    // bind hook to function that was substituted (copied to the prx) to make room for the loader
    SHK_BIND_HOOK( _shk_prx_elf_substitute, _shk_prx_elf_substitute_impl );
    
    LOADER_LOG( "runtime initialised\n" );
}

s32 _start( void )
{
    LOADER_LOG( "initialising\n" );
    initRuntime();

    // load config
    LOADER_LOG( "loading config\n" );
    configLoad( "/app_home/config.yml" );

    LOADER_LOG( "initialising modules\n" );
    for ( u32 i = 0; i < moduleGetModuleCount(); ++i )
        moduleInitModule( moduleGetModuleByIndex( i ) );
    
    return SYS_PRX_START_OK;
}

s32 _stop( void )
{
    LOADER_LOG( "shutting down\n" );

    LOADER_LOG( "shutting down modules\n" );
    for ( u32 i = 0; i < moduleGetModuleCount(); ++i )
        moduleShutdownModule( moduleGetModuleByIndex( i ) );

    LOADER_LOG( "shutdown finished\n" );
    return SYS_PRX_STOP_OK;
}
